<a href="https://colab.research.google.com/github/Muntaha369/Waste-Classifier/blob/main/Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder , StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.linear_model import Perceptron    # Used for simple linear classification tasks.

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from tensorflow.keras.models import Sequential     # Sequential lets you build a neural network layer-by-layer in Keras.

from tensorflow.keras.layers import Dense     #Dense makes the final predictions
from tensorflow.keras.layers import Conv2D     # Conv2D extracts features
from tensorflow.keras.layers import Flatten    # Flatten reshapes them

from tensorflow.keras.layers import MaxPooling2D     # MaxPooling2D reduces size
from tensorflow.keras.layers import Dropout          # Dropout prevents overfitting

from tensorflow.keras.utils import to_categorical     # converts numeric class labels into one-hot encoded format for training classification models
from tensorflow.keras.utils import image_dataset_from_directory  # converts image into 2d array

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("phenomsg/waste-classification")

print("Path to dataset files:", path)

100%|██████████| 1.02G/1.02G [00:11<00:00, 93.3MB/s]

Extracting files...


Path to dataset files: /root/.cache/kagglehub/datasets/phenomsg/waste-classification/versions/1


In [26]:
train_dataset = image_dataset_from_directory(
    f"{path}",
    image_size=(128, 128),
    batch_size=32
)

Found 2902 files belonging to 4 classes.


In [37]:
# you can't directly access image like train_dataset[0] because tensorflow converted it into a batch not a dict or a tuples

# To access a specific image it's better to itterate over a batchsize
for images, labels in train_dataset.take(1):
    print("Shape of images batch:", images.shape)
    print("Shape of labels batch:", labels.shape)
    print("Example labels (first 5):")
    print(labels[:5].numpy())

#Anoter way to iterate over a batch
# images, labels = next(iter(train_dataset)) # iter  --> turns train_dataset into an iterator we can pull batches from
                                             # next  --> grabs the next batch; since our Dataset returns (image, label) pairs, each batch here comes out as a tuple: (images, labels)

# print(images[0]) # this is a particular image from a batch

print("\nClass Names:")
print(train_dataset.class_names)

Shape of images batch: (32, 128, 128, 3)
Shape of labels batch: (32,)
Example labels (first 5):
[1 3 2 1 2]

Class Names:
tf.Tensor(
[[[ 88.      212.      218.     ]
  [ 88.      212.      218.     ]
  [ 88.      212.      218.     ]
  ...
  [199.7959  187.26562 184.     ]
  [199.51758 191.71875 184.     ]
  [199.49414 192.09375 184.     ]]

 [[ 88.      212.      218.     ]
  [ 88.      212.      218.     ]
  [ 88.      212.      218.     ]
  ...
  [199.4873  192.20312 184.     ]
  [199.53613 191.42188 184.     ]
  [199.51758 191.71875 184.     ]]

 [[ 88.      212.      218.     ]
  [ 86.80957 213.81055 223.42871]
  [ 99.46875 200.65625 200.65625]
  ...
  [199.66699 189.32812 184.     ]
  [193.12793 193.20312 184.     ]
  [199.9834  184.26562 184.     ]]

 ...

 [[216.      207.26562 192.46875]
  [216.      206.59375 199.79688]
  [216.      210.67188 200.     ]
  ...
  [216.      215.5     210.17188]
  [216.      200.      200.     ]
  [216.      200.26562 200.     ]]

 [[216.      

In [39]:
images, labels = next(iter(train_dataset))

In [40]:
print(images.shape)
print(labels.shape)

(32, 128, 128, 3)
(32,)
